### ISSUE TITLE
add user not possible

### ISSUE THREAD

**Issue by mquantin** [UIUCLibrary/teams#108]
Hello, 

I'm using omeka S 3.2.3 with mariaDB 5.10 (mysql8)

I cannot add users to teams. nor new nor existing users. 
I receive this error
`TypeError: Argument 3 passed to Teams\Controller\UpdateController::addTeamUser() must be of the type int, null given, called in /home/epotec/htdocs/omeka-s/modules/Teams/src/Controller/UpdateController.php on line 411 and defined in /home/epotec/htdocs/omeka-s/modules/Teams/src/Controller/UpdateController.php:51`

The UI is buggy when choosing a role for the user (no dropdown options)
<img width="2160" alt="Capture d’écran 2023-01-26 à 12 58 53" src="https://user-images.githubusercontent.com/11961831/214832738-740e1df2-c04d-4643-ae7f-dc17608da75a.png">
And from the users pannel
<img width="2159" alt="Capture d’écran 2023-01-26 à 12 57 29" src="https://user-images.githubusercontent.com/11961831/214832815-504817fe-84c2-402f-b966-b81669cd163c.png">

Other fields are OK and working fine. 

when I check the content of the table in the database, it is empty. is it OK? 
```sql
MariaDB [epotec]> SELECT * FROM team_role;
Empty set (0,001 sec)
```

**Comment by alexdryden** [comment]
Hi @mquantin,

The module doesn't come with any pre-made roles, so you'll need to make one or more before you can add users to teams. If you click on "My Teams" you should see a "Roles" option appear below it. From there you should be able to click "Add new role" if you are logged in as a global admin. 

When deciding on permissions for Team Roles, keep in mind that the module doesn't grant any extra permissions that aren't already given by the user's core role (e.g. Supervisor, Author, etc.). So, for example, if you will need one team member to be able to edit the items created by another team member, then they will need to be a Reviewer or above and have a Team Role that includes the "Edit Resources" permission. 

I'll add in some better error/warning messages for cases like this where there are no roles created yet.

**Comment by mquantin** [comment]
oups 🤭 
thank you for this answer 🙏 
shame on me ! 🤫
