### ISSUE TITLE
omeka-S v4 compatibility

### ISSUE THREAD

**Issue by mquantin** [UIUCLibrary/teams#115]
What about a migration to omeka-S v4?

**Comment by alexdryden** [comment]
We generally wait for 2-3 patches before pushing new features out to our production tiers, and as a result we are generally a few months behind the latest release. But, based on some recent testing, I don't expect support for Omeka 4.x to be a very heavy lift, and you can probably expect it in mid-March.

**Comment by mquantin** [comment]
oh great !
looking forward to that next version in production !
