### ISSUE TITLE
csv imported items -> orphaned

### ISSUE THREAD

**Issue by mquantin** [UIUCLibrary/teams#139]
A user has performs  csv imports. The imported items doesn't belong to his default term. They go to "trash" (could be renamed "orphaned items" or "orphaned")

For info: 
Only one default team is assigned to the user.
The owner of the import job is the user (I can read it from the job logs)

So far I did'nt try to reproduce the bug by myself

Any idea?

**Comment by alexdryden** [comment]
I'll take a look. This is one area where I can add some test coverage. If you happen to have access to the CSV they used and it is something they are willing to share, could you send it to me at adryden3@illinois.edu?

**Comment by alexdryden** [comment]
I've not yet been able to reproduce this myself. I working with Omeka S 4.0.4, CSVImport 2.5.0 and Teams 4.0.0-rc3.

**Comment by mquantin** [comment]
From Alex: "The undo is basically deleting the content that was created, and the default behavior is to remove the current user’s team instead of deleting so that people don’t accidentally delete content being used by other teams. But for the undo action via CSV import, this is not a good behavior."
#142 is more explicit
