### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by gmembreno** [UIUCLibrary/teams#147]
This is the error when try to install.

Omeka S 4.0.4
 
Laminas\ServiceManager\Exception\ServiceNotFoundException
Unable to resolve service "Teams\Form\ConfigForm" to a factory; are you certain you provided it during configuration?

Detalles:

Laminas\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "Teams\Form\ConfigForm" to a factory; are you certain you provided it during configuration? in /site/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:559
Stack trace:
#0 /site/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(614): Laminas\ServiceManager\ServiceManager->getFactory('Teams\\Form\\Conf...')
#1 /site/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate('Teams\\Form\\Conf...')
#2 /site/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(171): Laminas\ServiceManager\ServiceManager->get('Teams\\Form\\Conf...')
#3 /site/vendor/laminas/laminas-form/src/FormElementManager.php(336): Laminas\ServiceManager\AbstractPluginManager->get('Teams\\Form\\Conf...', Array)
#4 /site/modules/teams/Module.php(210): Laminas\Form\FormElementManager->get('Teams\\Form\\Conf...', Array)
#5 /site/application/src/Controller/Admin/ModuleController.php(291): Teams\Module->getConfigForm(Object(Laminas\View\Renderer\PhpRenderer))
#6 /site/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->configureAction()
#7 /site/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /site/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /site/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /site/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#11 /site/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#12 /site/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#13 /site/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#14 /site/index.php(21): Laminas\Mvc\Application->run()

**Comment by alexdryden** [comment]
Hi @gmembreno, thanks for the report! Can you confirm which version of the module you are using and which installation method you used (e.g., from git, from .zip release).

**Comment by gmembreno** [comment]
Hi @alexdryden thanks for the response, the version of the module is 4.0.1, the method was from git, let me check if the problem persist from the .zip release

**Comment by alexdryden** [comment]
Hmm. I'm not able to generate the same error on a fresh install of Omeka S 4.0.4 with Teams 4.0.1 either through the git tag or through the .zip asset from the most recent GitHub release. The only way I'm able to reproduce that error is by deleting the ConfigForm Factory at `src/Service/ConfigFormFactory.php`. Double-check to make sure that file didn't somehow get deleted.

**Comment by gmembreno** [comment]
All working now from the .zip release, thanks for the help! Maybe the monkeys from the hosting are too tired hehe
